### ISSUE TITLE
508 - Datepicker and  sds dialog container

### ISSUE THREAD

**Issue by Parulbpatel** [GSA/sam-design-system#1138]
**Components Involved**
Datepicker, sds-dialog-container

**Expected Behavior**
Data Entry pages: ATO Expiration date  and Discard Draft Dialog pop up should be 508 compliant.
T2 Workspace: Download Dialog pop up should be 508 compliant.
1) AMP tool should not show any error on ATO Expiration Date.
2) AMP tool should not show any error on Discard Draft dialog pop up.
3) AMP tool should not show any error on Download dialog pop up.
4) Jaws should only read selected ATO Expiry Date when field has already date available, it should not read eg. date.

**Actual Behavior**
AMP tool shows confirmed violations on Expiration date and Discard Draft/Download Dialog pop up.
Jaws reads the ATO Expiration field’s placeholder text even though it has Date available.

**Your Environment**
Angular Version: 13
@gsa-sam packages version: X.Y.Z (Please list individually if all packages are not same version)

**Ticket Number**
Please provide your JIRA ticket number that is dependent on this fix. If there is none, please create
one to validate the issue once the fix has been released. DO NOT provide the url, please ONLY
provide the ticket number.
IAEMOD-10466
IAEMOD-16530

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.

![image](https://user-images.githubusercontent.com/82841107/225108539-dab3710c-bbbe-42b1-9f20-49ddf367e176.png)
![image](https://user-images.githubusercontent.com/82841107/225108652-2730cfa6-8b8c-47c7-beb5-fbe72927289c.png)
![image](https://user-images.githubusercontent.com/82841107/225108776-16d13c06-0844-4e03-9a0f-2808b1a19c8b.png)
![image](https://user-images.githubusercontent.com/82841107/225108747-5882d163-d37e-4f4f-93fe-8b3e1cbb8110.png)
Download dialog pop up:
![image](https://github.com/GSA/sam-design-system/assets/82841107/4b963a34-9ba5-4a95-ba9e-c011cae9b38c)
![image](https://github.com/GSA/sam-design-system/assets/82841107/db9ac5b0-56fc-4a40-8388-70622e0c34ce)

**Comment by cwolf10** [comment]
Hi,

I just checked on these. 

Datepicker: I am seeing these errors being reported by AMP, however the errors are coming from the Angular Material datepicker. Since we are pulling their components in, SDS does not have the ability to update these components. I have checked their issues and it seems like the Material devs have looked into these before are working as expected. For example [here](https://github.com/angular/components/issues/29575) is an issue opened re: inactive focusable element.

Dialog: I am not seeing these errors in any of our demos. If you are still seeing these errors please provide me a configuration so that I can reproduce on my machine.
