### ISSUE TITLE
Autocomplete field is not assigning right id for input.

### ISSUE THREAD

**Issue by knamburigsa** [GSA/sam-design-system#1388]
**Components Involved**
Please list the common component(s) involved that you're experiencing an issue with
Autocomplete component

**Expected Behavior**
How you expect the listed component(s) to function
Autocomplete formly component should set the correct id for 'for' attribute on the label.

**Actual Behavior**
How the listed component(s) actually function
There is mismatch between the id attribute in input and for attribute in the label for autocomplete component.
https://gsa.github.io/sam-layouts/?path=/story/responsive-layout--responsive-layout
![image](https://github.com/GSA/sam-design-system/assets/92172714/5fffeec5-cb54-450e-985d-c63f09244f9d)
![image](https://github.com/GSA/sam-design-system/assets/92172714/294f2df9-af65-4bd9-abd2-73a6a9548356)

**Your Environment**
Angular Version: X.Y.Z
@gsa-sam packages version: X.Y.Z (Please list individually if all packages are not same version)

**Ticket Number**
Please provide your JIRA ticket number that is dependent on this fix. If there is none, please create
one to validate the issue once the fix has been released. DO NOT provide the url, please ONLY
provide the ticket number.
IAE-XYZ

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.

**Comment by cwolf10** [comment]
@knamburigsa an update for formly-autocomplete was released with v16.0.4. The issue here appears to be that the autocomplete ID is being set programmatically without formly knowing about the custom ID. To address this specific instance, formly needs to be told to use this custom ID. Here is an example of how this can be done: https://github.com/GSA/sam-design-system/blob/master/libs/documentation/src/lib/storybook/formly/formly-autocomplete/formly-autocomplete-id/formly-autocomplete-id.component.ts#L84-L87

To help with preventing this mixup, I have added a warning that will print to the console if there is a mis-match between the ID used by the formly label and the ID assigned to the autocomplete's input. If you use the above example, this warning will not show as the labels will match. 

While looking into this issue I also noticed the ID was not being shared between formly and the autocomplete component when assigning the ID in the formly config or even when leaving the ID assignment to formly. I have fixed these cases with this update as well.

To demonstrate the discovered scenarios, as well as your original issue, I have created a page with three demos. The first shows the way to pass the custom ID along to formly. The next shows passing a custom ID into the formly config and the last shows not assigning an ID and leaving that up to formly. Clicking each of the labels will result in the user focusing on the respective autocomplete, showing that the IDs are matching.

Link to the new demo: https://gsa.github.io/sam-design-system/?path=/story/formly-autocomplete--id
