### ISSUE TITLE
Not able to navigate dropdowns with arrow keys properly.

### ISSUE THREAD

**Issue by rithvik-mandalapu-gsa** [GSA/sam-design-system#1454]
**Components Involved**
Any component with a dropdown auto complete. 

**Expected Behavior**
When clicking drop down then hitting enter and using arrow keys, should be able to navigate through options.

**Actual Behavior**
Unable to navigate through options until typing something. 

**Your Environment**
Angular Version: 16.2.12
@gsa-sam packages version: 16.0.16

**Ticket Number**
IAEMOD-24943 (3rd bullet point), note: as stated above this issue is not limited to this component alone.

**Comment by cwolf10** [comment]
@rithvik-mandalapu-gsa is there a demo on our documentation site that has this unexpected behavior? If not, can you provide a sample configuration so that I can reproduce the behavior you are seeing in my local environment?

Also, please confirm these steps to re-produce the issue you are reporting: 
1) Click anywhere on the dropdown
2) Press the enter key
3) Use arrow keys to navigate through options - This is the point where the actual behavior differs from what you expect.
