### ISSUE TITLE
508 - Placeholder text for date range picker is being read incorrectly using screen readers.

### ISSUE THREAD

**Issue by knamburigsa** [GSA/sam-design-system#1457]
**Components Involved**
Please list the common component(s) involved that you're experiencing an issue with
daterangepicker - https://github.com/GSA/sam-design-system/blob/ng16/libs/packages/sam-formly/src/lib/formly/types/daterangepicker.ts

**Expected Behavior**
How you expect the listed component(s) to function
Place holder text should not have special characters so that screen readers can read it correctly.

**Actual Behavior**
How the listed component(s) actually function
As the current placeholder text has special characters, eg: May12, 2024. Screen readers are reading special characters with '\' prefixed.

**Your Environment**
Angular Version: 16
@gsa-sam packages version: X.Y.Z (Please list individually if all packages are not same version)
@gsa-sam/components: 16.0.8
@gas-sam/layout:16.1.1
@gas-sam/layouts:16.0.2
@gas-sam/sam-formly:16.0.8
@gas-sam/shared:16.0.18

**Ticket Number**
Please provide your JIRA ticket number that is dependent on this fix. If there is none, please create
one to validate the issue once the fix has been released. DO NOT provide the url, please ONLY
provide the ticket number.
IAEMOD-9154

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.

https://github.com/GSA/sam-design-system/assets/92172714/1bc48f3b-8fdb-4411-bd32-7ce2b3bedeca

**Comment by cwolf10** [comment]
This is not an issue with SDS.

I am able to reproduce this on the [basic datepicker demo](https://gsa.github.io/sam-design-system/?path=/story/formly-datepicker--basic) and as you can see in the HTML for this demo there is no backslash in any of the text read from this demo

<img width="397" alt="image" src="https://github.com/GSA/sam-design-system/assets/72805180/816cf3cd-6555-464f-9c0c-3a84f8f018a7">

Upon further research, this is a known issue with JAWS as reported in [issue 500](https://github.com/FreedomScientific/standards-support/issues/500). Once this issue is addressed by the JAWS team, the placeholder will be read without the additional character.
