### ISSUE TITLE
sds-filters -> filterChange emits on null during initialization, should not

### ISSUE THREAD

**Issue by jesseboydgsa** [GSA/sam-design-system#427]
if filterChange see's a null value on initialization DO NOT emit a filterChange

![image](https://user-images.githubusercontent.com/58823468/100160574-b5678600-2e64-11eb-8e6d-f1c44a0631cc.png)

**Comment by jesseboydgsa** [comment]
workaround 
![image](https://user-images.githubusercontent.com/58823468/100160754-08d9d400-2e65-11eb-9742-e5a31a9c01f0.png)

**Comment by Bibek-Regmi** [comment]
this is an issue on demo side rather than with the filters. The filterChange$ variable is of type `BehaviourSubject`, and `BehaviourSubjects` have the unique attribute of emitting the last known value whenever something subscribes to it. In this case, the `filterChange$` variable was initialized with a value of null, so it emitted null on subscription. You can prevent this by simply changing the data type of `filterChange$` on your application to `Subject` rather than `BehaviourSubject`  as they don't have that property. I will update the demo on our side as well to do the same.
