### ISSUE TITLE
Reset All not working properly after switching domains 

### ISSUE THREAD

**Issue by KidanyGSA** [GSA/sam-design-system#444]
Scenario: Search a keyword "test" in Assitance Listings, then switch to Contract Opp and the keyword chip should be preserved. 
If I click on reset all the chip goes away but the url history will now show the keyword and the results will still be filtered by the original keyword search.

![image](https://user-images.githubusercontent.com/66032295/101067293-60fb8f00-3565-11eb-8966-6697710b29e2.png)

**Comment by Bibek-Regmi** [comment]
The behavior seen here is caused by a change to the field configs on domain change. When we initialize a formly form with defined values in the data model, the values of that model are considered default values for the form as defined here - https://formly.dev/examples/field-options/default-value. And when clicking reset all, formly will reset the values to those default values. In this case, when you type `test` in Assistance Listing, and navigate domain to Contract Opportunities, your model contains the keyword entry with 'test' as value, and your field config changes. So formly initializes your new fields with the given model, setting the keyword `test` as a default value. Hence, when you click reset all, the keyword will switch back to `test`.

One potential solution to get the behavior you're looking for, maybe you can save a copy of the model before switching domains, reset your model, then change your fields. Then after formly applies the changes with new fields, re-add the model into your form using the copied model

**Comment by KidanyGSA** [comment]
I see, the issue is that my initialization doesn't have any values it is just //filterModel = {}; 
then we update the sds-toolbar configuration and only after that we update the filterModel. 
See image below.
Does updating the formly fields configuration creates a new instance of sds-toolbar??

![image](https://user-images.githubusercontent.com/66032295/104499307-e7ff4680-55aa-11eb-9fe4-bae13d39de68.png)

**Comment by Bibek-Regmi** [comment]
Updating field config does not create a new instance of sds-toolbar. What it does is update the default values of the formly form using the values of the filter model at the instance in which the update occurs
