### ISSUE TITLE
Formly Search not working in 10.0.0-beta.4

### ISSUE THREAD

**Issue by ascreven-gsa** [GSA/sam-design-system#458]
I'm still getting errors with reading template options for Formly Search after updating to Components 10.0.0-beta.4 and sam-formly 10.0.0-beta.4
<img width="1045" alt="Screen Shot 2020-12-14 at 11 21 02 AM" src="https://user-images.githubusercontent.com/63304927/102120146-565fb600-3dff-11eb-9eaf-c7ef63ec20c2.png">
<img width="747" alt="Screen Shot 2020-12-14 at 11 21 21 AM" src="https://user-images.githubusercontent.com/63304927/102120148-56f84c80-3dff-11eb-8450-afc9d52d5176.png">
<img width="376" alt="Screen Shot 2020-12-14 at 11 22 07 AM" src="https://user-images.githubusercontent.com/63304927/102120149-56f84c80-3dff-11eb-9df7-c1e458c418af.png">
<img width="352" alt="Screen Shot 2020-12-14 at 11 22 40 AM" src="https://user-images.githubusercontent.com/63304927/102120150-5790e300-3dff-11eb-904d-0b2a8f95f1a0.png">

It's difficult to see what's been changing in each Beta 10 release and to ensure the latest 10 Federalist build is being referenced but the documentation for branch IAE-44578 says the (modelChange) output is depreciated but is still using it in the example...

<img width="1680" alt="Screen Shot 2020-12-14 at 11 20 47 AM" src="https://user-images.githubusercontent.com/63304927/102120135-53fd5c00-3dff-11eb-9325-31bc57d25865.png">

**Comment by cwolf10** [comment]
Fixed in sds-formly@10.0.1.

Also clarification, (modelChange) as an output is not deprecated. The underlying model, whose update triggers (modelChange), is now being updated to what the current model is rather than only being updated when the search icon is clicked. As a result (modelChange) cannot be used to determine when the search icon is clicked, as it has in the past, submitHandler should be used as it will only be called when the search icon is clicked.
