### ISSUE TITLE
Sds-Search input field taking 1 letter then emitting value

### ISSUE THREAD

**Issue by jesseboydgsa** [GSA/sam-design-system#479]
Expected when I type in sds-search input box it will let me type a complete word and THEN click magnifying glass icon to complete my query.

Actual: I type one letter and it is emitted before i finish type and before I click search icon

library @gsa-sam/components 10.0.2

![image](https://user-images.githubusercontent.com/58823468/103427595-f6933a00-4b76-11eb-9958-579b3969fbfb.png)

**Comment by cwolf10** [comment]
Hi @jesseboydgsa ,

This is expected behavior added with https://github.com/GSA/sam-design-system/pull/439. For handling when a user has clicked the search icon, there is a field called submitHandler which has been added to the templateOptions for this field. It will call the function provided to it when the user clicks the search icon.

If you have further questions on behavior or want to see how to update your formly config, check out the demo that was added with this change Form Controls > Search > Submit Handling
