### ISSUE TITLE
Accessibility checks using JAWS for actions menu component (sds-actions-menu)

### ISSUE THREAD

**Issue by SeanKimGSA** [GSA/sam-design-system#588]
**Components Involved**
Please list the common component(s) involved that you're experiencing an issue with
sds-actions-menu

**Expected Behavior**
Actions menu in results should read the same as Actions menu in sub-header. 

**Actual Behavior**
Sub-header reads: "Actions button menu". Results action menu reads: "Toggle Actions menu heading level 3 button menu".

**Your Environment**
Angular Version: X.Y.Z
Angular: 10.2.3

@gsa-sam packages version: X.Y.Z (Please list individually if all packages are not same version)
"@gsa-sam/components": "10.0.9",
"@gsa-sam/layout": "10.0.10",
"@gsa-sam/layouts": "10.0.9",
"@gsa-sam/sam-formly": "10.0.9",
"@gsa-sam/sam-material-extensions": "10.0.9",
"@gsa-sam/sam-styles": "0.0.99",
"@gsa-sam/shared": "10.0.10",

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.
![image](https://user-images.githubusercontent.com/79326342/108542608-f29bb280-72b1-11eb-8097-4e419eb97791.png)

**Comment by Bibek-Regmi** [comment]
@SeanKimGSA - Updated so that the toggle button will instead say 'Toggle Actions Button Menu`. Not entirely sure where the heading level 3 is coming from as I do not see that in our demo site. In terms of the Expected Behavior reported in this issue, I'm seeing one button with 'Actions' label and another is a default menu button in your screenshot. Those two buttons have different content, and JAWS should announce them differently.

**Comment by Bibek-Regmi** [comment]
Closing to do inactivity
