### ISSUE TITLE
Giant X (closing icon) on toasts component and extra description label

### ISSUE THREAD

**Issue by KidanyGSA** [GSA/sam-design-system#671]
**Components Involved**
Toasts

**Your Environment**
Angular Version: 10
@gsa-sam packages version: X.Y.Z (Please list individually if all packages are not same version)
![image](https://user-images.githubusercontent.com/66032295/114416097-550c8300-9b7e-11eb-8715-7148616c8b24.png)

**Additional context**
Here we can see the X icon after the icon changes were done in SDS and also we can see that now we have some additional unnecessary description that wasn't previously there on the previous SDS versions in this case "success" word prior to the success icon.
![image](https://user-images.githubusercontent.com/66032295/114415421-a9fbc980-9b7d-11eb-8931-498187377fd2.png)

**Comment by Bibek-Regmi** [comment]
@KidanyGSA will be resolved in next release - 10.0.21 - The close button and the screen reader message - Success - were both referencing font awesome classes. These will be updated to use bootstrap icon and uswds class. There is an additional change in that previously we were showing the close button if the toast options' closeButton property was false - which is inverse of how someone might expect the property to work. This will be updated such that the close button is shown when toast options' closeButton property is true. So you might not see the close button for toast when you update because the default now is to not show it, and need to additionally set your toast options' closeButton property to true

**Comment by KidanyGSA** [comment]
Ok thanks for the heads up, we will be adding that property.

**Comment by Bibek-Regmi** [comment]
@jesseboydgsa - Could you validate on this as kidany is no longer in the program. It should no longer be an issue as of 10.0.21

**Comment by jesseboydgsa** [comment]
gm bibek this is no longer an issue ;)
