### ISSUE TITLE
Sds side navigation - 508 non unique accessible name for nav component.

### ISSUE THREAD

**Issue by rtencic-gsa** [GSA/sam-design-system#675]
**Components Involved**
sds-side-navigation

**Expected Behavior**
No Amp violations  -- nav element requires unique accessible name to differentiate nav element existing within the side nav component vs the header component. Component should assign a unique aria-label within sds-side-nav and header components

Assumption - aria label for nav element needs to be set at the design component level and should not be passed in from a higher level 

**Actual Behavior**
AMP is throwing a confirmed violation - This nav does not have an accessible name as required when two or more nav elements are present.

**Your Environment**
SDS 10.0.20

**Ticket Number**
IAEDEV-47484

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.
![nav 508 issue](https://user-images.githubusercontent.com/79877133/114610079-84e68400-9c6d-11eb-9704-cace0218bfe0.JPG)

**Comment by Bibek-Regmi** [comment]
@rtencic-gsa - Sds side navigation component will accept ariaLabel as an input that defines the label as of version 10.0.25. As we can't assume we know the context in which the side navigation is used (IE - navigation panel for entity information would have a different aria label vs navigation panel for help section) , the component itself cannot generate a hard coded descriptive label for the side nav, which is why we're allowing users to pass the description in.

**Comment by rtencic-gsa** [comment]
Issue resolved
