### ISSUE TITLE
History removing value types and causing issues in app rendering and logic flows

### ISSUE THREAD

**Issue by jesseboydgsa** [GSA/sam-design-system#703]
**Components Involved**
Please list the common component(s) involved that you're experiencing an issue with
sds-filters

**Expected Behavior**
How you expect the listed component(s) to function
i expect history to preserve the value and type of value.  booleans -> booleans, numbers -> numbers.  not convert all to strings.  agency picker chip to load on re-load showing correct UI to user.

**Actual Behavior**
How the listed component(s) actually function
agency picker fails to load chip on re-load because agency number is converted to a string see screenshot.  booleans converted to string will fail falsy checks.

**Your Environment**
Angular Version: X.Y.Z
@gsa-sam packages version: X.Y.Z (Please list individually if all packages are not same version)
![image](https://user-images.githubusercontent.com/58823468/117051920-eb3e4f80-accb-11eb-9bd9-595b428af370.png)

**Ticket Number**
Please provide your JIRA ticket number that is dependent on this fix. If there is none, please create
one to validate the issue once the fix has been released. DO NOT provide the url, please ONLY
provide the ticket number.
IAEDEV-50720

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.

this image shows the filtermodel 1st on reload with url params in history, 2nd filtermodel is correct values with chip showing.  model uses a number not a string.
![image](https://user-images.githubusercontent.com/58823468/117052226-5556f480-accc-11eb-9279-a4b0cb41b141.png)

**Comment by Bibek-Regmi** [comment]
@jesseboydgsa - This is a won't fix from design side. Since the only way to retrieve data is from url, there isn't any good way to differentiate between string vs numbers when retrieving data from url - we can't assume everything that can be parsed as number should be. Normally, it's the application implementing formly that can distinguish between which values should be numbers vs strings. Each formly config has a `parsers` property that you can give it - a list of functions to execute whenever the model updates. You could try adding parsers to your config for data that you expect to be numeric
