### ISSUE TITLE
Potential fix for sort value not carrying over switching domains

### ISSUE THREAD

**Issue by PeterWhiteGSA** [GSA/sam-design-system#715]
search-list-layout.component.ts

This function will check for the current sort value in the incoming array on sort values.
![image-2021-05-19-15-03-07-040](https://user-images.githubusercontent.com/84515469/118993856-79146e80-b94b-11eb-8405-37f7ebf4abef.png)

If present it will return a boolean value of true; else false. This can be used in a ternary operator when setting the new sortField on page change and page initialize.
![image-2021-05-19-15-07-16-654](https://user-images.githubusercontent.com/84515469/118993918-86c9f400-b94b-11eb-8eab-9711da3534b1.png)

This will let the list component determine whether to carry over the list order from the previous filter or use the default sort order.

**Comment by Bibek-Regmi** [comment]
@PeterWhiteGSA - The behavior of sort field reverting to default value of the domain is intended by design versus carrying over the sort field - even if the sort field is a valid sort field in the new domain. Switching domain is not seen as additional filter criteria but rather a soft reset to search filters.

**Comment by PeterWhiteGSA** [comment]
I'm going to need more clarification before moving forward with this issue.

**Comment by Bibek-Regmi** [comment]
@PeterWhiteGSA - Can you elaborate more on what you need clarification on? This ticket assumes sort value not carrying over on domain change is a bug. By design, sort value should not carry over when switching domain, so the behavior you're seeing is intended. If you'd like to programmatically change sort value due to some application specific business rules, then you can call `updateSearchResultsModel` method with the desired `sort` value in search-list-layout to do so
