### ISSUE TITLE
when user navigates to next/prev page user is redirected to the top of result list

### ISSUE THREAD

**Issue by jesseboydgsa** [GSA/sam-design-system#730]
**Is your feature request related to a problem? Please describe.**
When user clicks page up/down in sds-resultlist or selects a new page number they are not directed back to top of page.  internally sds-resultlist uses pagination component.

**Describe the desired solution**
User selects new page number and is directed back to top of page results

**Describe alternatives you've considered**
while i can listen to page events and create logic within search to navigate to the top of page, i believe this is better handled globally for a consistent app wide experience

**Additional context**
IAEDEV-51805 [US] Navigate to the top of the page when a user clicks previous/next page button

We do not want to navigate to top of page when user enters in a filter value and turned off  RouterModule.forRoot(routes, {
      scrollPositionRestoration: 'enabled', // Add options right here
    })
scrollPositionRestoration is now 'disabled' as instructed to do by Shilpa.

**Comment by cwolf10** [comment]
Hi @jesseboydgsa, v10.0.31 has updated the logic so that when scrollPositionRestoration  is 'enabled' the page is not scrolled when a user applies a filter. The page will still scroll when it would have scrolled previously. You should be able to pull this new version and update the scrollPositionRestoration property and see this issue resolved.

**Comment by jesseboydgsa** [comment]
tested and looks good thanks @cwolf10
